### ISSUE TITLE
Use of an already opened file descriptor object as a parameter, instead of a Path like object.

### ISSUE THREAD

**Issue by raulocana** [mrcagney/kml2geojson#17]
I want to implement a service that dynamically converts KML files to GeoJSON ones, the problem is that I do not have the file saved in my backend rather I received it as a bytes file descriptor, and I would rather use it as an already opened file descriptor than save the received object to then use the `convert` function and manage to delete it again.

Would it be possible to add support for a file descriptor as an option?

I think it would require the library to think of the received object as the opened `src`, and start reading from it with the `read()` method, bypassing the code to open it from a path.

I'm really interested in that feature, please let me know what you think!

**Comment by tonofshell** [comment]
I second this. Being able to use a file object would greatly increase the utility of this package. Limiting the package to using file paths works fine when you just want to convert a file locally. However, it makes it much less useful as a part of a larger software tool, that may or may not be running locally.

**Comment by araichev** [comment]
Thanks for the feedback @raulocana .
I'm not doing any development on this project at present, but i can make the time if you or other keen beans would like to pay for this feature.
I'll price it at 1500 NZD.

**Comment by araichev** [comment]
Found some funding and implemented this feature.
