### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by addelll** [mrcagney/kml2geojson#9]
The directory '/Users/slash/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/slash/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting kml2geojson
  Downloading kml2geojson-4.0.2.tar.gz
Requirement already satisfied: click>=6.6 in /Library/Python/2.7/site-packages (from kml2geojson)
Installing collected packages: kml2geojson
  Running setup.py install for kml2geojson ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Kt46U5/kml2geojson/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0mhPaa-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/kml2geojson
    copying kml2geojson/__init__.py -> build/lib/kml2geojson
    copying kml2geojson/cli.py -> build/lib/kml2geojson
    copying kml2geojson/main.py -> build/lib/kml2geojson
    running install_lib
    running install_data
    copying LICENSE.txt -> /System/Library/Frameworks/Python.framework/Versions/2.7/
    error: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/LICENSE.txt'
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Kt46U5/kml2geojson/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0mhPaa-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-Kt46U5/kml2geojson/

**Comment by araichev** [comment]
Hi there, looks like you're trying to install kml2geojson using Python 2.7, which is not supported in this version.  
That could be the problem.

On that note, i'm open to others submitting a patch for Python 2.7 compatibility as a merge request.
